### ISSUE TITLE
Environment creation error

### ISSUE THREAD

**Issue by suraj1988** [udacity/fcnd-issue-reports#106]

**Comment by suraj1988** [comment]
Hey there,Im on a Windows os. Ive installed git and miniconda., and cloned the starterkit directory. 
An error pops up when im creating the environment (Attached screenshot). It appears a required file is missing.
Any help would be appreciated.Thanks.
![FCND_environment_creation_error.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a964fc97feba00013617bbd/125516c66e82c728ace21e0d46ceb7b407bd86a799e0ad4caa50f59a3d7924612c05b7227f8bdc2dad5074134d435cec03070511afbd9b21b4b36d768b5f03ecd3645d7d933510acb88018ec52ec28884d97aaaec81d9ebc6278bec1da0d2c1417198ef55c30a19043c858f348e54856a1017b.PNG)

**Comment by jtuckerdunn** [comment]
Multiple students have experienced this setup error.

**Comment by suraj1988** [comment]
Fixed it. The issue seems to be with the shapely file.  For some reason it only seems to work if i manually download a shapely wheel and then modify the environment. yml file to point to the downloaded wheel. After that i have to update the fcnd from the terminal. Hope that helps if you're trying to find a workaround

**Comment by jtuckerdunn** [comment]
Changed shapely pip install to conda install in environment.yml file after reproducing the error on a windows computer and the issue seems to be fixed. Will leave this issue open for more testing.

**Comment by jtuckerdunn** [comment]
Fixed
