### ISSUE TITLE
Udacidrone Docs: ValueError: cannot reshape array of size 1 into shape (2) when running the demo Plotting Realtime Data

### ISSUE THREAD

**Issue by binliu-base** [udacity/fcnd-issue-reports#108]
I ran into a "ValueError: cannot reshape array of size 1 into shape (2)" when try to 
plot the NED position with visdom. 

the visdom-tutorial link
https://udacity.github.io/udacidrone/docs/visdom-tutorial.html

Figure out cause is there are two statements wrong

line: 11:  ne = np.array(self.local_position[0], self.local_position[1]).reshape(-1, 2)
line: 19:  d = np.array(self.local_position[2])

Which should be:
ne = np.array((self.local_position[0], self.local_position[1])).reshape(-1, 2)

and 

d = np.array([self.local_position[2]])

**Comment by JechoVarta** [comment]
np.array([self.local_position[0], self.local_position[1]]) 
can be written as 
self.local_position[:2]

**Comment by JechoVarta** [comment]
previous comment will not work, must change self.t to a list in the np.array([]) @ line 21

**Comment by domluna** [comment]
This should be fixed, reopen if it’s not the case

**Comment by amay1212** [comment]
Hi All, 

I'm getting the error like:--

states_next = states_next.reshape((batch_size, ) + self.input_shape)
ValueError: cannot reshape array of size 1001 into shape (1,10,10,10)

Whereas,my batch_size is 1 and input_shape is 1000.

Please help me to fix this.

Thanks!!
