### ISSUE TITLE
Bug Udacidrone Docs:visdom-tutorial not work

### ISSUE THREAD

**Issue by binliu-base** [udacity/fcnd-issue-reports#109]
I ran into a "ValueError: cannot reshape array of size 1 into shape (2)" when try to 
plot the NED position with visdom. 

the visdom-tutorial link
https://udacity.github.io/udacidrone/docs/visdom-tutorial.html

Figure out cause is there are two statements wrong

line: 11:  ne = np.array(self.local_position[0], self.local_position[1]).reshape(-1, 2)
line: 19:  d = np.array(self.local_position[2])

Which should be:
ne = np.array((self.local_position[0], self.local_position[1])).reshape(-1, 2)

and 

d = np.array([self.local_position[2]]) 

After update the two statements, visdom works.

**Comment by jtuckerdunn** [comment]
This issue is a duplicate with #108. This ticket is being closed and archived.
