### ISSUE TITLE
Simulator does not work with "simple" graphics

### ISSUE THREAD

**Issue by Shreeyak** [udacity/fcnd-issue-reports#112]
It works for me if I click on "good"  or "best" quality, but not on "simple". The screen goes black with only the HUD and the quad itself visible. 
Please see video below.

**Comment by Shreeyak** [comment]
File too large. please refer to video uploaded in beta testers channel in slack. https://udacity-flying-car.slack.com/files/U7708BW72/F9HHPMB0F/fcnd-sim-error.mp4

**Comment by ryan-keenan** [comment]
This is fixed with the new sim version.  Please reopen this issue if the problem persists. Thanks!
