### ISSUE TITLE
Sim graphics - Road "flickering" at the point where 3 roads intersect.

### ISSUE THREAD

**Issue by Shreeyak** [udacity/fcnd-issue-reports#113]
Please see the video here: https://udacity-flying-car.slack.com/files/U7708BW72/F9HHPMB0F/fcnd-sim-error.mp4

**Comment by jtuckerdunn** [comment]
@domluna Please reassign to Noam if he is the best one to fix issues like this. I'm not sure what his email is.

**Comment by demi180** [comment]
Roads are improved in newer version of sim, if that's not available yet it will be soon.

**Comment by ryan-keenan** [comment]
This is no longer an issue because we've upgraded to a new environment. Enjoy the new sim!
