### ISSUE TITLE
3D motion planning review - What is acceptable error from goal position

### ISSUE THREAD

**Issue by Shreeyak** [udacity/fcnd-issue-reports#115]
What if the quad lands at a position away from the goal position? What kind of error is acceptable?

**Comment by jtuckerdunn** [comment]
This is a rubric question.

**Comment by Shreeyak** [comment]
Yes, this is regarding the rubric point v

**Comment by ryan-keenan** [comment]
Meant to do this earlier, but just updated the rubric to say we're not requiring a particular accuracy for arriving at the goal.  This will mostly be determined by the acceptance radius for waypoints defined in `local_position_callback()`, so students who don't change that will land within 1 m of goal.  If they choose to expand the acceptance radius (deadband) for waypoints they might land further away.  not a problem.
