### ISSUE TITLE
3D motion Planning - Please add requirement to explain code in readme

### ISSUE THREAD

**Issue by Shreeyak** [udacity/fcnd-issue-reports#116]
None of the criteria actually require one to write an explanation of the code.
Please add in a requirement to explain each of the steps in the write-up. If they are not present in the write-up, then that rubric point gets failed.

**Comment by ryan-keenan** [comment]
Sounds good.  I'll update you when the rubric is updated.

**Comment by ryan-keenan** [comment]
At some point I added language about explaining your code in the writeup for certain rubric points. Hopefully that does the trick! I'll close this now but feel free to reopen if it seems like the rubric could be better still
