### ISSUE TITLE
No solution branch in udacity/FCND-Backyard-Flyer

### ISSUE THREAD

**Issue by tjphoton** [udacity/fcnd-issue-reports#12]
In lesson 3.12, I don't see solution branch of the backyard flyer in github. I only see the following 10 branches: master, cli, cleanup, ws, make-global-position-ints, patch223, meters, fix-conda, event_driven, event_driven2.

**Comment by silentwater** [comment]
Can confirm this issue. The solution branch doesn't exist so one can't follow the instruction given in chapter 3.12.

**Comment by adrnp** [comment]
branch is up: https://github.com/udacity/FCND-Backyard-Flyer/tree/solution
