### ISSUE TITLE
In "Quaternion Exercise", inconsistent np.array_equal is used

### ISSUE THREAD

**Issue by xcarnd** [udacity/fcnd-issue-reports#123]
In "Quaternion Exercise", in the last python statement of the exercise jupyter notebook, `np.array_equal` is used for comparing floating point numpy array, which is not consistent. Shall use `np.allclose` or other consistent floating point comparison methods instead.

**Comment by jtuckerdunn** [comment]
This ticket was accidentally closed and was recreated as issue 126
