### ISSUE TITLE
The solution for Bresenham exercise is inaccessible

### ISSUE THREAD

**Issue by hayaalsh** [udacity/fcnd-issue-reports#125]
The solution for Bresenham exercise cannot be accessed and the following error message appears: "This page expects to be used for Udacity class content. Please make sure you are accessing this content from a Udacity lesson."

**Comment by ryan-keenan** [comment]
Thanks for reporting!  Just fixed this. You'll need to go to "Menu" in the bottom left of your notebook workspace and select "Reset data"
