### ISSUE TITLE
In "Quaternion Exercise", inconsistent np.array_equal is used

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#126]
In "Quaternion Exercise", in the last python statement of the exercise jupyter notebook, np.array_equal is used for comparing floating point numpy array, which is not consistent. Shall use np.allclose or other consistent floating point comparison methods instead.

**Comment by jtuckerdunn** [comment]
This is a copy of ticket 123 by @xcarnd which was accidentally closed.

**Comment by ryan-keenan** [comment]
Thanks for reporting this.  Sorry that took so long but fixed now!
