### ISSUE TITLE
Collinearity testing for 3d points seems not right

### ISSUE THREAD

**Issue by xcarnd** [udacity/fcnd-issue-reports#127]
After doing some search I think for 3 arbitrary points in 3-dimensional space, determinant = 0 is not sufficient to claim the points are collinear. 

One counter-example: 
```
p1 = np.array([1, 1, 0])
p2 = np.array([1, -1, 0])
p3 = np.array([-1, -1, 0])
print("Det: ", np.linalg.det(np.vstack((p1, p2, p3))))
```

The resulting det = 0 yet these points are apparently not collinear.

**Comment by ryan-keenan** [comment]
Thanks for reporting! yeah seems like something's broken here I'll look into this

**Comment by ryan-keenan** [comment]
The collinearity exercise was definitely wrong about this, I've revised it to be focused on the 2D case and noting that for the 3D case det=0 is a necessary but not sufficient condition for collinearity.  Thanks for pointing this out!
