### ISSUE TITLE
Bizarre drone behavior when "ARM" is pressed (Ubuntu 17.10)

### ISSUE THREAD

**Issue by AndyAtUdacity** [udacity/fcnd-issue-reports#130]
A student working on the backyard flyer project mentioned: 

> I downloaded the latest simulator for Ubuntu 17.10, When I arm the drone, it just goes crazy. Flies around everywhere randomly without maintaining attitude, as though some one threw it. Anyone else experienced this?

The student's name on Slack is Vishwa

**Comment by jtuckerdunn** [comment]
This issue is being merged with #118
