### ISSUE TITLE
Copy/Paste from local machine to VM

### ISSUE THREAD

**Issue by Sagar-Jarvis** [udacity/fcnd-issue-reports#132]
Copy/Paste from local to VM is a quite elaborate one. If we can directly copy/paste stuff to VM and from VM without the use of clipboard that would be great!

**Comment by ryan-keenan** [comment]
Agreed!  I added your note to the instructions that you can open a browser in the VM and copy/paste directly. I'll ask the workspaces team about whether better copy/paste support is on their roadmap but for now we just need to suffer ;)
