### ISSUE TITLE
Project 2 motion planning simulator reset

### ISSUE THREAD

**Issue by gantners** [udacity/fcnd-issue-reports#140]
When testing the backflyer solution in the beginning it is Needed to do multiple resets on the sim with SHIFT+R.
Also the Position various from reset to reset. It Switches between two positions, one in the City one outside

**Comment by domluna** [comment]
@demi180 is working on a fix

**Comment by jwdunn1** [comment]
Also, after a reset (on the second try) in Motion Planning all the trees are missing. The buildings return, but not the vegetation. (v0.1.0 Simulator and v0.1.0 Motion Planning)

**Comment by domluna** [comment]
@jwdunn1 The most recent versions don't have the fix for this yet. I'll post an update here when we have a version that does. Should be soon

**Comment by jtuckerdunn** [comment]
@domluna has this issue been fixed?

**Comment by demi180** [comment]
Yes, we’ll have a new release by tomorrow.

**Comment by jwdunn1** [comment]
Has the new release been delayed?
