### ISSUE TITLE
5.15 Configuration space exercise solution is buggy

### ISSUE THREAD

**Issue by lxfind** [udacity/fcnd-issue-reports#141]
It does grid assignment without boundary checking. For instance, grid[-35:35, 1:2] = 1
When you do that, the negative number gets interpreted differently (e.g. -X becomes size - X), so you end up with an entirely wrong range.

**Comment by domluna** [comment]
@ryan-keenan does this sound like it would be fixed with the new updates?

**Comment by ryan-keenan** [comment]
yep this is fixed now, thanks for reporting!
