### ISSUE TITLE
4.14 A* Wrong Triangle Inequality Theorem

### ISSUE THREAD

**Issue by lxfind** [udacity/fcnd-issue-reports#143]
The theorem should use <= instead of <, otherwise Manhattan distance will never be a valid heuristics.
Also refer to the wikipedia pages:
https://en.wikipedia.org/wiki/Triangle_inequality
https://en.wikipedia.org/wiki/Admissible_heuristic

**Comment by ryan-keenan** [comment]
Thanks for reporting! I'll look into this

**Comment by ryan-keenan** [comment]
Ok I've put in a request to edit that graphic but unfortunately Nick says "less than" instead of "less than or equal" so we'll have to live with it in the audio for now.

**Comment by ryan-keenan** [comment]
The video has now  been updated to show "<=" which is all we can do for now. Hopefully isn't too misleading that Nick says "less than" as that appears on screen.
