### ISSUE TITLE
4.10: in BFS jupyter notebook add queue details to be imported as a TODO comment

### ISSUE THREAD

**Issue by 10manjunath** [udacity/fcnd-issue-reports#144]
In Lesson 4, chapter 10, Breadth-First exercise, add this comment.
"TODO: import queue module"

currently its like this:
\# Import numpy and Enum
import numpy as np
from enum import Enum

**Comment by ryan-keenan** [comment]
Just did a major overhaul of this exercise.  The code is essentially the same but with way more explanation up front and better comments.  Thanks for the suggestion!

**Comment by 10manjunath** [comment]
Why is the path variable initialized twice in the breadth_first function? I think one of them should be deleted

**Comment by 10manjunath** [comment]
And there's another major error in printing path. In breadth_first function, towards the end, while loop

```
while branch[n][0] != start:
            path.append(branch[n][0]) #THIS ZERO SHOULD BE ONE
```

**Comment by ryan-keenan** [comment]
Thanks for the feedback!  I removed the first initialization of `path`.  For the other thing you mention, that 0 is a 1 in the default notebook, so maybe try "Reset data" and you'll get the same.
