### ISSUE TITLE
6.8 Bresenham Exercise solution is buggy

### ISSUE THREAD

**Issue by lxfind** [udacity/fcnd-issue-reports#145]
The solution follows this pseudocode:
if f(x+1) > y + 1:
    y += 1
else:
    x += 1

which forgets the case when f(x + 1) = y + 1.
The proper code should look like:
if f(x+1) > y + 1:
    y += 1
elif f(x + 1) == y + 1:
    x += 1
    y += 1
else:
    x += 1

Otherwise in the case of y2 - y1 = x2 - x1, you would always be drawing unnecessary blocks along the line.

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  Indeed there was something missing here.  However, I see it as a possibility for two different approaches. On the one hand, if your obstacle cells really represent physical obstacles, you wouldn't want to plan a path through a grid corner flanked by two obstacles, such that in the event that `f(x+1) == y+1` you'd want to flag all cells that share that corner as in collision.  On the other hand, if you've padded obstacles with a safety margin already you're probably fine just incrementing both x and y and flagging only cells that are in direct collision.  Anyway, check it out and see if you agree with the modified implementation!
