### ISSUE TITLE
Backyard Flyer, Simulator bug in Debug mode

### ISSUE THREAD

**Issue by saurav-joshi** [udacity/fcnd-issue-reports#146]
1. Start the project in PyCharm. 

2.Run the debug mode. 

3. Stop at a callback by applying a breakpoint and wait for sometime. 

4. resume the execution.

5. The Application gets abruptly killed.

**Comment by domluna** [comment]
@saurav-joshi By application you mean the simulator or pycharm? Can you provide the Player.log file, https://docs.unity3d.com/Manual/LogFiles.html

**Comment by domluna** [comment]
Closing. Reopen if more info is provided.
