### ISSUE TITLE
Code error in L8.5 "Modeling Dynamics Exercise"

### ISSUE THREAD

**Issue by xcarnd** [udacity/fcnd-issue-reports#147]
In the initial notebook, the `simulate` function defined in the 3rd code cell shall be renamed to `model`, which is referenced later in the same notebook.

**Comment by ryan-keenan** [comment]
Thanks for catching this!  some last minute renaming of functions happened here.  if you "Reset data" on this notebook you'll find the updated version where both are called `simulate()`
