### ISSUE TITLE
FCND Simulator intro page background

### ISSUE THREAD

**Issue by jwdunn1** [udacity/fcnd-issue-reports#148]
Reads: "Self-Driving Car Engineer" under the stretchy Udacity logo. (v0.1.0 Simulator)

**Comment by domluna** [comment]
@demi180

**Comment by domluna** [comment]
@ryan-keenan can we get a new logo ?

**Comment by demi180** [comment]
@domluna the new sim fixed this, right?

**Comment by jtuckerdunn** [comment]
@domluna Has this been fixed?

**Comment by demi180** [comment]
Yes, will show up in new release
