### ISSUE TITLE
Minor bugs in the plotting codes in L8.11 RRT Exercise

### ISSUE THREAD

**Issue by xcarnd** [udacity/fcnd-issue-reports#152]
The code used for plotting the initial node:

```plt.plot(x_init[0], x_init[1], 'ro')```

shall be:

```plt.plot(x_init[1], x_init[0], 'ro')```

In the exercise, both x_init[0] and x_init[1] are set to 50 so it is hard to notice the wrong parameter order.

**Comment by domluna** [comment]
@xcarnd Thanks for catching this,  it's been updated. :+1:
