### ISSUE TITLE
Planning code for Exercise 6.13 is buggy

### ISSUE THREAD

**Issue by lnson** [udacity/fcnd-issue-reports#155]
I ran A* on non-inverted skeleton and found this bug. Some of the bound checks in valid_actions are not correct. For example:
if (x - 1 < 0 and y - 1 < 0) or grid[x - 1, y - 1] == 1:
should be
if x - 1 < 0 *or* y - 1 < 0 or grid[x - 1, y - 1] == 1:
?

**Comment by ryan-keenan** [comment]
Ah yes indeed! I thought I fixed this the other day but seems it's still in there.  Thanks for reporting it should be fixed now.
