### ISSUE TITLE
Probabilistic Roadmap example

### ISSUE THREAD

**Issue by GustavoMonge** [udacity/fcnd-issue-reports#162]
Probabilistic Roadmap
In this notebook you'll expand on previous random sampling exercises by creating a graph from the points and running A*.

Load the data
Sample nodes
Connect nodes
Visualize graph
Define heuristic
Define search method
Execute and visualize
We'll load the data and provide a template for visualization.

# Again, ugly but we need the latest version of networkx!
import sys
!{sys.executable} -m pip install -I networkx==2.1
import pkg_resources
pkg_resources.require("networkx==2.1")
import networkx as nx
Collecting networkx==2.1
 Downloading networkx-2.1.zip (1.6MB)
   100% |████████████████████████████████| 1.6MB 397kB/s eta 0:00:01  9% |███                             | 153kB 4.6MB/s eta 0:00:01    45% |██████████████▋                 | 737kB 5.9MB/s eta 0:00:01
Collecting decorator>=4.1.0 (from networkx==2.1)
 Downloading decorator-4.2.1-py2.py3-none-any.whl
Building wheels for collected packages: networkx
 Running setup.py bdist_wheel for networkx ... done
 Stored in directory: /root/.cache/pip/wheels/a0/33/4e/7c9228ea77f8090e895d8d2b76f3b5a76997a5b3edeb4e2c6f
Successfully built networkx
Installing collected packages: decorator, networkx
Successfully installed decorator-4.2.1 networkx-2.1
---------------------------------------------------------------------------
VersionConflict                           Traceback (most recent call last)
<ipython-input-1-522c6390d28b> in <module>()
     3 get_ipython().system('{sys.executable} -m pip install -I networkx==2.1')
     4 import pkg_resources
----> 5 pkg_resources.require("networkx==2.1")
     6 import networkx as nx

/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py in require(self, *requirements)
   982         included, even if they were already activated in this working set.
   983         """
--> 984         needed = self.resolve(parse_requirements(requirements))
   985
   986         for dist in needed:

/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
   873                 # Oops, the "best" so far conflicts with a dependency
   874                 dependent_req = required_by[req]
--> 875                 raise VersionConflict(dist, req).with_context(dependent_req)
   876
   877             # push the new requirements onto the stack

VersionConflict: (networkx 1.11 (/opt/conda/lib/python3.6/site-packages), Requirement.parse('networkx==2.1'))

nx.__version__ # should be 2.1

**Comment by ryan-keenan** [comment]
Thanks for reporting! This install fails sometimes for unknown reasons.  I've added another comment with the suggestion to "reset and clear output" from the "Kernel" menu and try again.  Sorry for the clunkiness but we're stuck with this until we update some exercises in another program that rely on the earlier version of networkx.
