### ISSUE TITLE
Mistake in video subtitles

### ISSUE THREAD

**Issue by subamrana** [udacity/fcnd-issue-reports#163]
On this link: https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/0c12632a-b59a-41c1-9694-2b3508f47ce7/lessons/c9b7c43f-6c90-401a-a2ce-ac10613e34f1/concepts/d39a4af2-2996-462b-b77c-2937562df489

The subtitles of the video of "16. Summary" of "Lesson 4 : Planning as Search" has a mistake at 0:29 timestamp.

'date' should be 'state'.

**Comment by aurinalam** [comment]
Fixed. Thank you!
