### ISSUE TITLE
Mistake in subtitles

### ISSUE THREAD

**Issue by subamrana** [udacity/fcnd-issue-reports#164]
Link: https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/0c12632a-b59a-41c1-9694-2b3508f47ce7/lessons/91ccafae-d090-4144-a8f3-06cb8ac10757/concepts/48b68581-c0fa-419a-b559-e836da78dc42

Lesson 5 Flying car representation, "1. Thinking like a drone".

In this video, there is a mistake in subtitles at timestamp 0:51.

'all' angles should be 'euler' angles.

**Comment by aurinalam** [comment]
Fixed. Thank you!
