### ISSUE TITLE
skiprows not updated when colliders.csv changed format

### ISSUE THREAD

**Issue by Mark70117** [udacity/fcnd-issue-reports#165]

**Comment by Mark70117** [comment]
data = np.loadtxt('colliders.csv', delimiter=',', dtype='Float64', skiprows=3)
https://github.com/udacity/FCND-Motion-Planning/blob/6b14950b9ddcae940126b1eb87db6d4716e68306/motion_planning.py#L134

colliders was changed, but not this line which skips past the "posX" header
so now first colliders is missed

skips first row of data.  colliders.csv  used to start
lat0,lon0
37.792480,-122.397450
posX,posY,posZ,halfSizeX,halfSizeY,halfSizeZ
-305,-435,85.5,5,5,85.5

now starts
lat0 37.792480, lon0 -122.397450
posX,posY,posZ,halfSizeX,halfSizeY,halfSizeZ
-310.2389,-439.2315,85.5,5,5,85.5

**Comment by ryan-keenan** [comment]
Great catch! Just pushed this fix now thanks.
