### ISSUE TITLE
Discrepancies between rubric and udacidrone API

### ISSUE THREAD

**Issue by darienmt** [udacity/fcnd-issue-reports#166]
There are some problems on some points of the 3D Motion Panning rubric(https://review.udacity.com/#!/rubrics/1534/view).

“In the starter code, we assume the drone takes off from map center, but you’ll need to be able to takeoff from anywhere. Retrieve your current position in geodetic coordinates from self._latitude(), self._longitude() and self._altitude(). Then use the utility function global_to_local() to convert to local position (using self.global_home() as well, which you just set)” 

self._latitude(), self._longitude() and self._altitude() are not functions on udacidrone API.

**Comment by Mark70117** [comment]
it should read "self._latitude, self._longitude and self._altitude" removing "()" as they are variables, not functions.

https://github.com/udacity/udacidrone/blob/master/udacidrone/drone.py#L19

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  Fixed now :)
