### ISSUE TITLE
Mistake in subtitles

### ISSUE THREAD

**Issue by subamrana** [udacity/fcnd-issue-reports#167]
Link: https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/0c12632a-b59a-41c1-9694-2b3508f47ce7/lessons/91ccafae-d090-4144-a8f3-06cb8ac10757/concepts/c8739456-e992-4afa-96d7-a0b290230170

Lesson 5 Flying Car Representation, 6. Body Frame

At timestamp 0:33, it should be 'IMU' instead of 'INU'.

**Comment by aurinalam** [comment]
Fixed. Thanks for reporting!
