### ISSUE TITLE
Lesson 8.12 Better Steering exercise

### ISSUE THREAD

**Issue by tjphoton** [udacity/fcnd-issue-reports#171]
At the end of Rick's lecture of this lesson (1:19), he mentioned "in the next exercise, you will implement this modification to your steering function." I don't see any exercise related to this lesson.

**Comment by ryan-keenan** [comment]
Thanks for reporting this! Actually we've removed this video for now because it doesn't seem like the "better steering" method is needed for this lesson.  Will update on this ticket if we reinstate it and add an exercise.
