### ISSUE TITLE
Lesson 3.5 From Grids to Graphs: Collinearity Exercise

### ISSUE THREAD

**Issue by davinderc** [udacity/fcnd-issue-reports#174]
There is a paragraph near the bottom before the Collinearity Exercise section. The sentence here is excessively long and potentially confusing to students. I had a mentee bring it up and after looking at it, I could see how it could cause confusion for the student initially. Could we split this sentence into two to make it clearer?

**Comment by ryan-keenan** [comment]
Thanks for reporting! Fixed this yesterday :)
