### ISSUE TITLE
Incorrect A* implementation

### ISSUE THREAD

**Issue by lnson** [udacity/fcnd-issue-reports#175]
Detailed description here:
https://udacity-flying-car.slack.com/files/U9HB89676/F9RSYSYJ0/mvimg_20180318_203555.jpg

**Comment by ryan-keenan** [comment]
Thanks for reporting this! Another student also reported the same issue (I believe) in the classroom implementation so I've updated both the project code and the instances of A* in the classroom.  I'll close this for now but feel free to reopen if issues persist.
