### ISSUE TITLE
Project 2 motion planning error

### ISSUE THREAD

**Issue by tjphoton** [udacity/fcnd-issue-reports#178]
starter code works fine.
But when asked in # TODO: set home position to `(lat0, lon0, 0)`, it should be `(lon0, lat0, 0)`.
I was confused why drone keep drifting to the south east direction. But if commenting out the self.set_home_location(lat0, lon0, 0), it works fine. Took me quite a while to figure this out.

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  Fixed now in the repo.
