### ISSUE TITLE
Error running command on Workspace

### ISSUE THREAD

**Issue by Ayshine** [udacity/fcnd-issue-reports#180]
ıtried to use workspace and got permission denied error while running below command on terminal.

./FCND-Sim_Linux_64-bit

**Comment by ibadr** [comment]
Same error.

![error](https://user-images.githubusercontent.com/13662993/37855935-2d656086-2ec8-11e8-9d2f-387c5acf70c7.PNG)

Issuing
```
chmod +x ./FCND-Sim_Linux_64-bit
```

solves the problem.

**Comment by ryan-keenan** [comment]
Thanks for offering the fixing ibadr! This should be fixed now in the default version of the workspace.
