### ISSUE TITLE
Lesson 11.19 PID Control Exercise Code Cell #3 does not run

### ISSUE THREAD

**Issue by tjphoton** [udacity/fcnd-issue-reports#194]
Lesson 11.19 PID Control Exercise, the 3rd code cell does not run. `z_dot_dot_ff` is missing. 
Either add `z_dot_dot_ff = 0` before line `controller.thrust_control()` (because z = -1, z_dot = 0, z_dot_dot = 0, for all t)
or remove `z_dot_dot_ff` from `controller.thrust_control()` argument list, since the default value is set to 0.

**Comment by tjphoton** [comment]
The two lines are not needed. These are for the previous exercise.
```
AMPLITUDE = 0.5
PERIOD    = 0.4
```

**Comment by AndyAtUdacity** [comment]
Both issues fixed
