### ISSUE TITLE
Lesson 4.10 "Breadth First Exercise" error in code representation

### ISSUE THREAD

**Issue by init927** [udacity/fcnd-issue-reports#196]
The first line of Code says to add Start(1,0) place and then adding this place as visited in next code, It should print out (1,0) rather than (0,0) as visited the place.

**Comment by init927** [comment]
![Screen Shot 2018-03-25 at 1.46.42 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aaba37e76b5e600112b4160/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f66b7191a379f1162d4f5b5d5ecc3c4a4356bcbbd671f3e57862804e0ebcd76c5c7cc73f18aeb1d717be01ba228c1cd6e0b4894ed2f42f67b6d5db1063474f4dcbed5727a19141c95df44ae84b52a0133667ef7f2431.png)

**Comment by ryan-keenan** [comment]
Thanks for reporting this! Fixed now :)
