### ISSUE TITLE
In L10.23 Controller 2D Drone, target omega shall be in opposite sign

### ISSUE THREAD

**Issue by xcarnd** [udacity/fcnd-issue-reports#197]
The resulting omegas for  `set_rotors_angular_velocities` shall be in opposite signs to get rotational equilibrium.

**Comment by VladimerUdacity** [comment]
While you need to be careful regarding the propeller rotation direction in co-axial drone case, characterizing the propeller angular velocities by its value is sufficient in the 2D drone case. As in the 2D drone, torques are created by force generated by propeller times the distance of the propeller from the center of the mass. Contrary to the co-axial drone when torques along the z-axis were created by reactive force by counterrotating propellers. Thus, in 2D case, you need to keep track of the value of the angular velocity and not the sign of it.
