### ISSUE TITLE
(Peter Rho) Lesson 2 - Item 6. Motors / Speed Controllers - Typo

### ISSUE THREAD

**Issue by perh70** [udacity/fcnd-issue-reports#2]
(Peter Rho) Lesson 2 - Item 6. Motors / Speed Controllers - Typo in the following sentence: "Suppose your power supply has an operating range is 3-7 volts" instead of "range is 3-7 volts" it should be "range between 3-7 volts"

Here's URL to the page:
https://classroom.udacity.com/courses/ud787-preview/lessons/35850006-650e-483f-a46f-c3a58809cbf0/concepts/983fa26c-24df-4eb0-8142-8afa49bf5ae6

**Comment by AndyAtUdacity** [comment]
Fixed!
