### ISSUE TITLE
Bug in Sampler.sample ?

### ISSUE THREAD

**Issue by imsut** [udacity/fcnd-issue-reports#203]
I think there is a bug in the way random points are discarded in Sampler.sample() method in Lesson 7 - 9.
Basically, for a random point S, it picks a Polygon (= obstacle) whose center is closer to S than a center of any other Polygon to S, and checks if that Polygon contains S.
I don’t think this check is enough.

Let’s assume, in 1-D version for simplicity, there are two obstacles A and B. A is centered at 0 with half-width 1 while B centered at 7 with half-width 5
Now we have a randomly sampled point S at 3. A will be picked up as its center (0) is closer to S (distance 3), than B (distance 4).
A does not contain S; S won’t be discarded per this logic.
B, however, does contain S. S should be discarded in fact.

**Comment by ryan-keenan** [comment]
Thanks for raising this issue and sorry for the delayed response. You are definitely correct that the logic in Sampler.sample breaks down when obstacle polygons have different shapes. That implementation was written back when all colliders were 10x10 m in size! Now however, we have trees and in principle colliders could be whatever shape or size.  I've updated `Sampler.sample()` to be a wee bit smarter and check for collisions with any polygons that are within a radius equal to the size of the largest polygon in the map.  Could be more clever, but this should at least avert the issue you raised above.  Keep the great feedback coming!
