### ISSUE TITLE
Lesson 4.10 "Breadth First Exercise" Spelling Mistake

### ISSUE THREAD

**Issue by init927** [udacity/fcnd-issue-reports#205]
Spelling Error in the word "Exercise". Follow this paragraph.-> In this "execise", you'll keep track of which cells you can..... Spelling Error in Exercise.

**Comment by init927** [comment]
![Screen Shot 2018-03-26 at 10.48.12 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aaba37e76b5e600112b4160/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f56b7191a379ef0c2f59415e4cbc21254d58eeb9cb74fce36f34985619e8806b5e77ce3c13a5ba8b4ab700ba208948d6e5ea824fc2fa2137a5dad11b61435c52dcbd4f3fb29b49c259f349e34d5da01a346ae471336e0a.png)

**Comment by ryan-keenan** [comment]
Thanks for catching that!  fixed now :)
