### ISSUE TITLE
Lesson 8.11

### ISSUE THREAD

**Issue by mcavaioni** [udacity/fcnd-issue-reports#207]
Error in the solution 
----> 6     for v in rrt.vertices:
      7         d = np.linalg.norm(x_rand - np.array(v[:2]))
      8         if d < closest_dist:

TypeError: 'method' object is not iterable

**Comment by apostbr** [comment]
The RRT class needs to be updated. The "edges" and "vertices" are methods, not properties.  

  @property
    def vertices(self):
        return self.tree.nodes()
    
    @property
    def edges(self):
        return self.tree.edges()

**Comment by ryan-keenan** [comment]
Thanks for reporting this and for posting a fix to the problem! I've updated the notebooks in the classroom now.
