### ISSUE TITLE
A* Reporting action list instead of path

### ISSUE THREAD

**Issue by mkontz** [udacity/fcnd-issue-reports#208]
There seems to be a new bug in A* when A* is imported using "from planning import a_star".  I am currently working through Lesson 7.  Yesterday, A* was reporting the path correctly, but the cost was too large (see Issue 187).  This evening, the cost has been fixed, but A* is reporting the action list instead of the path.  I noticed this because the plots of the paths stopped working today.

**Comment by ryan-keenan** [comment]
Sorry for the delay but thanks again for reporting this!  Should be fixed in all classroom instances now.
