### ISSUE TITLE
Lesson 2.6 quantumdevices hyperlink has been changed

### ISSUE THREAD

**Issue by kampta** [udacity/fcnd-issue-reports#21]
Link in the lesson - https://quantumdevices.wordpress.com/2010/08/27/brushless-motors-vs-brush-motors-whats-the-difference/ 

has been moved to

http://www.quantumdev.com/brushless-motors-vs-brush-motors-whats-the-difference/

**Comment by jtuckerdunn** [comment]
This is the same as issue #16
