### ISSUE TITLE
Typo in Lesson 14 Full 3D Control Exercise, solution.py

### ISSUE THREAD

**Issue by tjphoton** [udacity/fcnd-issue-reports#211]
Inside the attitude_controller() definition, `yaw_controller` is mis-spelled as `yaw_contorller()'. 
The spelling in the `yaw_controller()` definition is correction.

**Comment by tjphoton** [comment]
Lesson 14 Full 3D Control Exercise, solution.py
Inside the attitude_controller() definition, `yaw_controller` is mis-spelled as `yaw_contorller()`. 
The spelling in the `yaw_controller()` definition is correction.

**Comment by AndyAtUdacity** [comment]
Fixed spelling in solution.py
