### ISSUE TITLE
clarify Lesson 14 Full 3D Control Exercise 3.2 Advance state function

### ISSUE THREAD

**Issue by tjphoton** [udacity/fcnd-issue-reports#212]
It's not clear in the TODO that a new state need to be returned. I thought it just like advance_state(), only need to set private variables. 
But in the later "Executing the flight" section, new state is assigned to a variable, rather than directly accessed by `drone.X`. So `return self.X` is necessary. Suggest to make this clear.
```
drone_state = drone.advance_state(dt/inner_loop_relative_to_outer_loop)
```

**Comment by AndyAtUdacity** [comment]
Fixed by adding descriptive comment underneath the "TODO"
