### ISSUE TITLE
Broken link in Lesson 14.8 Euler's Equations in a Rotating Frame

### ISSUE THREAD

**Issue by tjphoton** [udacity/fcnd-issue-reports#213]
missing a right bracket:

correct link: 
https://en.wikipedia.org/wiki/Euler%27s_equations_(rigid_body_dynamics)

link in the lesson:
https://en.wikipedia.org/wiki/Euler%27s_equations_(rigid_body_dynamics

**Comment by AndyAtUdacity** [comment]
Fixed!
