### ISSUE TITLE
Voronoi graph excercise missing +1 causing path not to match collisions.

### ISSUE THREAD

**Issue by annerajb** [udacity/fcnd-issue-reports#218]

**Comment by annerajb** [comment]
>  grid[obstacle[0]:obstacle[1]+1, obstacle[2]:obstacle[3]+1] = 1
This line is on the solution but it's missing the +1 on the excersise notebook.

This causes that even if the algorithm requested on the exercise is correctly implemented the path collide with the building and appear to go thru them.

**Comment by ryan-keenan** [comment]
Great catch! Thanks for reporting this. Fixed now.
