### ISSUE TITLE
motion_planning.py msgpack error

### ISSUE THREAD

**Issue by GuidoManfredi** [udacity/fcnd-issue-reports#220]

**Comment by GuidoManfredi** [comment]
When trying to run motion_planning.py, I get the following error:
"ModuleNotFoundError: No module name 'msgpack'.

I am using ubuntu 17.10
FCND env is activated

**Comment by mkontz** [comment]
I received the same error in Windows.

**Comment by ryan-keenan** [comment]
Thanks for reporting this, `msgpack` was a fairly late addition to the Python starterkit.  Can you double check that it exists in the `environment.yml` file you installed? If not you'll need to update your FCND env to include it.  I'll assume this is solved but please feel free to reopen the ticket if not!

**Comment by ryan-keenan** [comment]
`environment.yml` should look like this: https://github.com/udacity/FCND-Term1-Starter-Kit/blob/master/environment.yml
