### ISSUE TITLE
networkx version conflict

### ISSUE THREAD

**Issue by Robock** [udacity/fcnd-issue-reports#225]
Graph Search Exercise notebook solution in Lesson 7 Section 15 has problem that has to do with the networkx version conflict.

**Comment by Robock** [comment]
Resolved the issue by resetting and clearing output from the Kernel menu as suggested. Thanks

**Comment by ryan-keenan** [comment]
Thanks for reporting Robock! In the future we shouldn't need to do this ugly install, but glad to hear it resolved after retry.
