### ISSUE TITLE
Dibins Car excercise

### ISSUE THREAD

**Issue by GustavoMonge** [udacity/fcnd-issue-reports#226]
Possible ERROR:

The Dubin's Car is expressed with the following differential equations: 

x˙=v∗cos(θ)
y˙=v∗sin(θ)
θ˙=tan(u)

The third term is missing the velocity as given by the solution code

θ˙= v∗tan(u)

The third term is function of the angular velocity, and in other words if the vehicle is not moving the change in orientation is always cero

**Comment by ryan-keenan** [comment]
Thanks for reporting this!  I finally got around to updating the notebook.  Definitely was incorrect to include the v in two places and not the third .
