### ISSUE TITLE
Lesson 7.13 Medial Axis

### ISSUE THREAD

**Issue by init927** [udacity/fcnd-issue-reports#227]
The Solution has White-Space in Function : find_start_goal(skel, start, goal):
1) start_min_dist
2) goal_min_dist

**Comment by init927** [comment]
![Screen Shot 2018-04-05 at 12.31.56 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aaba37e76b5e600112b4160/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276454f66b7191a379ed0c2850415a48bc21254d58eeb9cb74fce36f34985619e8806b5e77ce3c13a5ba8b4ab700ba208948d6e5ea824fc2fa2137a5dad11b61435c52dcbd4f3fb29842c259f349e34454a51a3167e67f376e0a.png)

**Comment by ryan-keenan** [comment]
Yeah that was ugly, thanks for reporting!  Fixed now.
