### ISSUE TITLE
P2: Issue on the online desktop

### ISSUE THREAD

**Issue by GaylouM** [udacity/fcnd-issue-reports#228]
During the environment setup, on the online desktop, impossible to activate the FCND conda environment. Error message: "bash: activate: no such file or directory" after running cd /opt
tar -xvf /home/workspace/miniconda3.tgz

**Comment by ryan-keenan** [comment]
Hi GaylouM, I just tried this and it worked for me. Can you try resetting the data in the workspace and give it another try? To do this, go to the IDE screen with "Go To Desktop" button in lower right and click on the "Menu" button and choose "Reset data".  Please reopen this ticket if that fails to solve your problem!

**Comment by GaylouM** [comment]
Perfect it works now.

Thank you

Regards

2018-04-07 22:12 GMT+02:00 ryan-keenan <notifications@github.com>:
