### ISSUE TITLE
Probabilistic-Roadmap Solution error

### ISSUE THREAD

**Issue by Robock** [udacity/fcnd-issue-reports#229]
The solution for the exercise in Lesson 8.9 seems to have the same networkx version conflict issue as previous exercises that I reported yesterday.

**Comment by Robock** [comment]
Resolved the issue by resetting and clearing output from the Kernel menu as suggested. Thanks

**Comment by ryan-keenan** [comment]
Thanks for reporting! Sorry for the ugly install :(
