### ISSUE TITLE
takeoff() and cmd_position() do not work

### ISSUE THREAD

**Issue by riturajtiwari** [udacity/fcnd-issue-reports#23]
I am able to launch ipython shell, connect to the drone and arm(). However, the suggested steps of drone.takeoff(3) and drone.cmd_position(5,0,3,0) don't have any effect. The disarm() control seems to work.

**Comment by riturajtiwari** [comment]
It started working after I restarted ipython.

**Comment by domluna** [comment]
@riturajtiwari was the drone armed and guided when you tried `takeoff` or `cmd_position`?

```
# enter guided mode and arm drone
drone.take_control()
drone.arm()
```

**Comment by domluna** [comment]
I'm going to close this, reopen if you're still having issues.
