### ISSUE TITLE
Is solution to in Lesson 11.23 correct?

### ISSUE THREAD

**Issue by lnson** [udacity/fcnd-issue-reports#230]
The solution makes both rotors spin CW, but this would make the vehicle rotate around the z axis?

```
    def set_rotors_angular_velocities(self,linear_acc):
        """
        Sets self.omega_1 and self.omega_2 to realize the desired
        linear_acc. Note that this is for vertical motion ONLY. It
        is assumed that rotational acceleration and phi is zero
        """
        omega = math.sqrt(self.m * (-linear_acc + self.g) /(2 * self.k_f))

        self.omega_1 = omega
        self.omega_2 = omega

        return self.omega_1, self.omega_2
```

**Comment by VladimerUdacity** [comment]
While you need to be careful regarding the propeller rotation direction in co-axial drone case, characterizing the propeller angular velocities by its value is sufficient in the 2D drone case. As in the 2D drone, torques are created by force generated by propeller times the distance of the propeller from the center of the mass. Contrary to the co-axial drone when torques along the z-axis were created by reactive force by counterrotating propellers. Thus, in 2D case, you need to keep track of the value of the angular velocity and not the sign of it.
