### ISSUE TITLE
Lesson 4.5 - Reference to Linux branch is incorrect.

### ISSUE THREAD

**Issue by tribbloid** [udacity/fcnd-issue-reports#233]
In this section, Dr Roy mentioned that Intel Aero's companion computer runs on Ubuntu, while the screenshot later clearly shows that the OS version is Poky Aero 1.6.1 (pyro)

[Poky is a reference distribution of the Yocto Project®](https://www.yoctoproject.org/software-item/poky/)

**Comment by adrnp** [comment]
the default os is yocto, I've added a reference to how to put ubuntu onto the computer as that is fully supported.  thanks for pointing out the potential source of confusion.
