### ISSUE TITLE
11.12 (Tracking Changes to State): should use old velocity to multiply dt

### ISSUE THREAD

**Issue by lxfind** [udacity/fcnd-issue-reports#238]
When updating z, the video uses the new z (that is, z after adding delta_z_dot) to multiply dt to get the distance traveled. This is counter-intuitive. Shouldn't it use the old z to multiply dt to compute the distance traveled? It only makes slight difference, but when you accumulate t to a very long span, the difference starts to matter.

**Comment by AndyAtUdacity** [comment]
You are correct, but for pedagogical reasons we wanted to highlight the double integration that's happening and decided this was a better way to do it. Thanks for the feedback.
