### ISSUE TITLE
14.5 Solution for Drone?

### ISSUE THREAD

**Issue by berndrietberg** [udacity/fcnd-issue-reports#239]
In the 3D drone exercise, exercise 1 of lesson 14, it is stated that:

$\bar{c} = \frac{F}{k_f} = \frac{c m }{k_f}$

However, in the solution there is a minus sign:
c_bar = -c * self.m / self.k_f

Why is this?

**Comment by VladimerUdacity** [comment]
Z-axis is directed down which means that the thrust needs to directed up. The up direction has the negative value when projected on the z-axis. consider that the gravity which is directed down has the positive sign.
