### ISSUE TITLE
index-error in the A-Star-City-Solution

### ISSUE THREAD

**Issue by ywiyogo** [udacity/fcnd-issue-reports#243]
In the 11-th step, it throws an index error. The variable `pp` only has 1 dimensional array.
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-11-1733def4d5ac> in <module>()
      7 
      8 pp = np.array(path)
----> 9 plt.plot(pp[:, 1], pp[:, 0], 'g')
     10 
     11 plt.xlabel('EAST')

IndexError: too many indices for array
```

**Comment by domluna** [comment]
@ywiyogo are you sure a path to the goal was found? The only case this should be 1D is in an empty array is returned.

**Comment by ywiyogo** [comment]
yes, the 10th step prints this:
```
Found a path.
1023 1023.0
```

**Comment by domluna** [comment]
can you share your code?

**Comment by ywiyogo** [comment]
The code is in the Udacity [solution in Lesson 7, section 9](https://view6ddbca99.udacity-student-workspaces.com/notebooks/A-Star-City-Solution.ipynb)

**Comment by domluna** [comment]
Added a note to the notebook related to the form the path should be in so it plots correctly.
