### ISSUE TITLE
Add additional material on accessory hardware with Intel Aero

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#246]
Lesson feedback: It would be good if you guys mentioned all the necessary hardware\, like the USB hub\, the HDMI adapter and all that the first time you mentioned the Aero. I purchased the Aero and pause the course\, then got the Aero and realized I needed more items\, that I just ordered\, and now I need to wait for those to arrive in order to get started with the drone.

**Comment by adrnp** [comment]
updated, thanks for the feedback!
