### ISSUE TITLE
Better Steering video mentions exercise that doesn't exist

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#252]
Either edit video to remove reference or add exercise.

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/0c12632a-b59a-41c1-9694-2b3508f47ce7/lessons/2329f84b-c055-4a9f-88d4-ba8583bd66c2/concepts/8739c940-ce9d-4491-ab06-649cba11a1dc

**Comment by ryan-keenan** [comment]
@jtuckerdunn this video is non-public for this reason. Future TODO could be to add an exercise.
