### ISSUE TITLE
Add solution to Potential Field Exercise

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#253]
There is no solution for the potential field exercise.

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/0c12632a-b59a-41c1-9694-2b3508f47ce7/lessons/2329f84b-c055-4a9f-88d4-ba8583bd66c2/concepts/cf1025da-d78a-4912-bfd2-82a47e478368

**Comment by domluna** [comment]
Added link to solution.
