### ISSUE TITLE
Probabilistic roadmap exercise implementation error

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#254]
I do not think that the Sampler implementation in sampling.py (in Lesson 8: Probabilistic Roadmap Exercise) is correct. For a given point\, it tries to find a colliding polygon by probing a polygon with the closest centroid. It is\, however\, very easy to construct a counter-example\, in which the point is inside some polygon\, but the polygon with the closest centroid does not overlap with the point at all.

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/0c12632a-b59a-41c1-9694-2b3508f47ce7/lessons/6e2a0873-e549-4045-a877-394ef572f93e/concepts/7f2d7afe-4775-4377-9fa4-167ce6431315

**Comment by ryan-keenan** [comment]
@jtuckerdunn I believe a student brought this up awhile ago and I fixed it (somewhat hacky, but solves this). Maybe reset data on the workspace and see if you get an updated version.
