### ISSUE TITLE
Blank background on startup

### ISSUE THREAD

**Issue by davinderc** [udacity/fcnd-issue-reports#26]
When I start the 64-bit bin, the background is blank until I change the resolution.

**Comment by davinderc** [comment]
![blankBackground.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/590eb1523e4a6c001a9500e9/125516c66e82c728ace21e0d46ea989b2d89a1a88ce2b851ab48fe906b0a65633b0ba92e7391a172fd177a575e5c46ad43515d4da9f1882ba6b43b23d90a03eed37f4366846c4ff8e7df46f554f832815d84b1b68b49c1ef3427e18a8c46381c030ac4.png)

**Comment by domluna** [comment]
Should be fixed in this release -> https://github.com/udacity/FCND-Simulator-Releases/releases/tag/v0.0.4-preview

**Comment by jtuckerdunn** [comment]
Closing this issue assuming it was fixed in release 4
