### ISSUE TITLE
Part 1, Lesson 2.7 - Typo

### ISSUE THREAD

**Issue by mbano** [udacity/fcnd-issue-reports#268]
Typo on question: "given it's weight" 
should be 
"given its weight"

**Comment by aurinalam** [comment]
https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/2c43620c-78cc-427f-afc1-e6e0d42f82f0/lessons/99905423-0638-479b-a9f5-d5f33de6c613/concepts/983fa26c-24df-4eb0-8142-8afa49bf5ae6

**Comment by AndyAtUdacity** [comment]
fixed!
