### ISSUE TITLE
Project: Backyard Flyer Lesson 9 typo

### ISSUE THREAD

**Issue by mbano** [udacity/fcnd-issue-reports#269]
The text reads:
"NOTE - the last few lines of the code below is where the EventDrivenChatBot class is instantiated and it's methods are called." 

this should be changed to:

"its methods are called"

**Comment by mbano** [comment]
For clarification, this refers to part 9 of the Project: Backyard Flyer section (rather than lesson 9)-

**Comment by aurinalam** [comment]
https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/2c43620c-78cc-427f-afc1-e6e0d42f82f0/lessons/13c0ca8d-b11e-405a-a831-6ca38cb60246/concepts/329dab52-39cd-46ad-9d81-6b94aeaf8c0f

**Comment by AndyAtUdacity** [comment]
fixed!
