### ISSUE TITLE
Part 2, Lesson 4.4 grammar mistake

### ISSUE THREAD

**Issue by mbano** [udacity/fcnd-issue-reports#271]
The text reads:

 "In general, it's always good to err on the side of caution in general."

this should be

 "In general, it's always good to err on the side of caution."

**Comment by aurinalam** [comment]
Hi @mbano - Thank you for reporting this. I am unable to find the lesson this is in. Can you please comment with the link to the classroom where this is? Thanks!

**Comment by AndyAtUdacity** [comment]
fixed!
