### ISSUE TITLE
Drone Integration, Lesson 4.8, wrong code shown

### ISSUE THREAD

**Issue by mbano** [udacity/fcnd-issue-reports#272]
The waypoint box is calculated as 

local_waypoints = [cp + [10.0, 0.0, 3.0], cp + [10.0, 10.0, 3.0], cp + [0.0, 10.0, 3.0], [0.0, 0.0, 3.0]]

This should be:

local_waypoints = [cp + [10.0, 0.0, 3.0], cp + [10.0, 10.0, 3.0], cp + [0.0, 10.0, 3.0], cp + [0.0, 0.0, 3.0]]

(the calculation of the last waypoint had not been updated to include the drone's current position at takeoff).

**Comment by adrnp** [comment]
thanks for pointing that out, fixed.
