### ISSUE TITLE
3D Motion Planning, Lesson 1.12 typo

### ISSUE THREAD

**Issue by mbano** [udacity/fcnd-issue-reports#274]
The text reads:

"Here we've added a third element each tuple defining actions, which is the cost of each action, and in this case is set to a value of one in for all actions." 

The end of this sentence should be :

 "one for all actions".

Additionally, the sentence 

"In this exercise you'll assign a cost to each action and you can even expand your action set to include diagonal motions of you like!" 

should read:

"if you like".

**Comment by AndyAtUdacity** [comment]
fixed!
