### ISSUE TITLE
Missing linked paper in Lesson 14 Full 3D Control, part 10

### ISSUE THREAD

**Issue by gabrcg** [udacity/fcnd-issue-reports#275]
The video points that papers will be linked to explain the mathematics provided there, but there are no papers attached.

**Comment by tribbloid** [comment]
The paper should explain transformation matrix T.
At  Lesson 14 Full 3D Control, part 10 Integrating PQR into the World Frame. 1:37

**Comment by AndyAtUdacity** [comment]
Added these links!
