### ISSUE TITLE
Intro to Estimation Lesson 16.5 - Video too long

### ISSUE THREAD

**Issue by aurinalam** [udacity/fcnd-issue-reports#278]
The video ends around 1:23, but the video goes on until 3:03 with a black screen. Would be good to cut the video. 

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/19b5af05-2ec7-491a-94db-1befc15d07c0/lessons/0aad84d9-ec84-42b6-8ed8-10d770055da4/concepts/3e39c4a6-154c-4195-aac6-a445d97063fc?contentVersion=1.0.0&contentLocale=en-us

**Comment by AndyAtUdacity** [comment]
This has been fixed.
