### ISSUE TITLE
12. Backyard Flyer (local development) clarity suggestion

### ISSUE THREAD

**Issue by dannyrjack** [udacity/fcnd-issue-reports#28]
I would possibly put a section(s) in "12. Backyard Flyer (local development)" that defines the final project, Box Mission, for clarity.

i.e. “For the final project, you will be flying the drone in a box. We’ve provided a working solution below of the drone flying in a 5x5m box at an altitude of X m. For your final project, you can determine your own box size and altitude.”

**Comment by AndyAtUdacity** [comment]
Good suggestion. Implemented.
