### ISSUE TITLE
In L18.15 Kalman Filter Exercise, the control input `u` is not properly initialized

### ISSUE THREAD

**Issue by xcarnd** [udacity/fcnd-issue-reports#281]
`u` shall be a vector (because there is only one control input \ddot z), but in the exercise, it is defined as a 2x1 matrix: 

> u = np.array([[0.0],
>                       [0.0]])

**Comment by VladimerUdacity** [comment]
The reasoning behind initializing u the way it is is that we need to make sure that matrix multiplications are performed accordingly. Also, a vector is nothing more than a single dimensional tensor, which 2D matrix with only 1 column or raw also satisfies. 
To reiterate. The u variable initialized as 
u = np.array([[0.0],
                       [0.0]])
maintains the u.shape() which is appropriate to execute numpy operations.
