### ISSUE TITLE
Why quadrotors quiz error

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#283]
In question 2 of the quiz "helicopters" should be replaced with "quadrotors"

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/2c43620c-78cc-427f-afc1-e6e0d42f82f0/lessons/99905423-0638-479b-a9f5-d5f33de6c613/concepts/4cd94c53-55b3-4061-b3cb-379a576e0c44

**Comment by AndyAtUdacity** [comment]
fixed
