### ISSUE TITLE
Error in Graph Search Exercise when run locally

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#287]
From: Lesson Feedback:

On the Graph Search Exercise (Lesson 7.15) I got a VersionConflict error when I tried to run the notebook online and a "ModuleNotFoundError: No module named 'grid'" when I tried to run it locally using the fcnd environment.

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/0c12632a-b59a-41c1-9694-2b3508f47ce7/lessons/5a623140-3e28-4ef1-a0f2-104715381c54/concepts/c766ccda-fc5f-4137-8bcf-5cf288318141

**Comment by AndyAtUdacity** [comment]
This is expected behavior. "grid" is just a .py file that was created for this lesson. It's not supposed to work locally.
