### ISSUE TITLE
Lec 17.14 missing a negative sign in the z component [0 0 g]^

### ISSUE THREAD

**Issue by fredchyan** [udacity/fcnd-issue-reports#291]

**Comment by fredchyan** [comment]
[Uploading 17.14.png...]

**Comment by AndyAtUdacity** [comment]
This isn't actually  an error. Z-axis points down so g should be positive.

**Comment by fredchyan** [comment]
@AndyAtUdacity  could you please take a look at my comments above? but regardless I think it's missing negative sign somewhere, because R [0 0 g] != [g sin theta; -g sin phi cos theta; -g cos phi cos theta]

**Comment by AndyAtUdacity** [comment]
Great catch and thank you for following up. You are absolutely right! I was clearly forgetting how accelerometers work :)

I'm going to add a note below the video indicating that this should be a -g

**Comment by dyfc** [comment]
@AndyAtUdacity Here we should be careful with which rotation matrix to use. it is not stated explicitly in the video but, in my opinion, R should be a matrix rotating from global frame to body frame:
![R-global2body.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5ac4d717c551090011b116f1/125516c66e82c728ace21e0d46dad99d2f8d81a883bbbd4ca044b2d86b56357c2301a03f32dfa17dbe142a52575e4ca543510a4cfdf98929a1e56f26825f09ffcd7f1d2598694ef1e1c84afd13b0328a468fb7b9884bc9ee3c23e78e8d483f0c48.png)

With this matrix, result of multiplication R*[0 0 -g].T is consistent with equation in video (at 1:30)
