### ISSUE TITLE
Potential Field Solution Notebook

### ISSUE THREAD

**Issue by jchernus** [udacity/fcnd-issue-reports#294]
Spelling mistakes in https://viewd03c0af3.udacity-student-workspaces.com/notebooks/Potential-Field-Solution.ipynb

I don't know how to fix this, but would be happy to learn. 

1)

"In this notebook you'll create a potential field by implement and combine attractive and replusive forces."

Should be implementing, combining. 

2)

Further down: "Recall from lecture and the attraction potential is:"

Should replace *and* with *that*.

**Comment by AndyAtUdacity** [comment]
It looks like you actually DID know how to fix this one. I think the fix probably just wasn't registering in the classroom :)
