### ISSUE TITLE
(Peter Rho) Lesson 2 - Item 6. Motors / Speed Controllers - Typo "it's"

### ISSUE THREAD

**Issue by perh70** [udacity/fcnd-issue-reports#3]
(Peter Rho) Lesson 2 - Item 6. Motors / Speed Controllers - Typo "it's" in sentence "The most important thing to know about a particular motor is it's so called "Kv" rating."

Here's URL to the page:
https://classroom.udacity.com/courses/ud787-preview/lessons/35850006-650e-483f-a46f-c3a58809cbf0/concepts/983fa26c-24df-4eb0-8142-8afa49bf5ae6

**Comment by AndyAtUdacity** [comment]
Fixed
