### ISSUE TITLE
error while setting up fcnd environment

### ISSUE THREAD

**Issue by AndyAtUdacity** [udacity/fcnd-issue-reports#30]
first terminal dump - [diyjac.txt](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59d3ce5e2799da0012d136d3/125516c66e82c728ace21e0d46ec9d83298380ebc3abaf51ab57f5973d047d317c05f57a23ddb27ae6102204575e4eac435f0c17aaf18a29b4aa2e32db025fb28c341521842f1bbeb98a15be04bb27824784b7bf8a4ac3e92f68.txt)

For more information, check out the #t1-p1-backyard-flyer channel on slack

**Comment by AndyAtUdacity** [comment]
This was reported by a student ( #diyjac in Slack)

**Comment by domluna** [comment]
if this is on ubuntu try `sudo apt-get install libxml2-dev libxslt-dev`

**Comment by davinderc** [comment]
This method seems to resolve the missing `future` module, but the pymavlink 2.2.0 seems to still have an issue installing: https://github.com/ArduPilot/pymavlink

**Comment by domluna** [comment]
Does changing pymavlink to 2.2.8 fix this?

**Comment by davinderc** [comment]
I've got it up and running now it seems (pymavlink and udacidrone both import without a word of warning). Haven't checked with the simulator though.

**Comment by domluna** [comment]
tested this on 16.04 with pymavlink 2.2.8 and it works so I'm closing this. The simulator issues https://github.com/udacity/fcnd-issue-reports/issues/26, etc are being worked on separately.
