### ISSUE TITLE
Math mentioned in video, missing below video

### ISSUE THREAD

**Issue by jchernus** [udacity/fcnd-issue-reports#301]
https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/b78ec22c-5afe-444b-8719-b390bd2b2988/lessons/adf9cc77-d52c-4958-810d-89ddc5997437/concepts/449a2563-db72-44ab-be5b-74bcb7d4993e

1:08: "Actual math is shown below".

But nothing shown below. However, it is shown on the next page.

Either add some math or cut out the last few seconds of the video.

**Comment by AndyAtUdacity** [comment]
Added a note clarifying that math appears on next page.
