### ISSUE TITLE
environment mixing

### ISSUE THREAD

**Issue by orenmeiri** [udacity/fcnd-issue-reports#32]
the code in "simulation exploration" is described in command line python environment while the next video, "the problem with sequential execution" is using jupyter notebook. this can be confusing for someone not familiar with different python environments. Maybe it is better to stick to one environment in all discussions and examples.

**Comment by AndyAtUdacity** [comment]
Part of the intention here was to show the command line in video so students see the similarities (since they're likely to encounter both in the future). I appreciate the suggestion but I think we're going to leave this as is.
