### ISSUE TITLE
Estimation for Quadrotors Eq 52

### ISSUE THREAD

**Issue by jwdunn1** [udacity/fcnd-issue-reports#320]
In the referenced paper here: https://www.overleaf.com/read/vymfngphcccj
On page 9, in equation 52, matrix row 1 column 2, the term **should read** "-\sin\phi \sin \theta \sin \psi - \cos \phi \cos \psi" to match transpose of Dieble 71. Specifically, after the second minus sign, "\cos \theta" needs to change to "\cos \phi".

**Comment by AndyAtUdacity** [comment]
Good catch! Just fixed this in the overleaf document!
