### ISSUE TITLE
closed caption error F equals MA

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#332]
1:06 - "subset" should be changed to "sub Z"

**Comment by aurinalam** [comment]
https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/b78ec22c-5afe-444b-8719-b390bd2b2988/lessons/4cd7a5c4-12ad-4853-86cb-759d3833e856/concepts/35af4878-8cc8-4d5e-b6d9-46d2f6fb5c2a?contentVersion=1.0.0&contentLocale=en-us

Fixed.
