### ISSUE TITLE
cc error controlling a 2D quad

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#334]
0:33 "talks" should be "torques"

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/b78ec22c-5afe-444b-8719-b390bd2b2988/lessons/4cd7a5c4-12ad-4853-86cb-759d3833e856/concepts/6cc55c76-a755-45f5-83f2-9da9068d0db2

**Comment by aurinalam** [comment]
Fixed
