### ISSUE TITLE
cc error lesson introduction

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#335]
0:18 "way" should be "weight"

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/b78ec22c-5afe-444b-8719-b390bd2b2988/lessons/dd98d695-14f1-40e0-adc5-e9fafe556f73/concepts/9763a631-a3d0-4443-8a94-5d60d2c93a17

**Comment by aurinalam** [comment]
Fixed
