### ISSUE TITLE
cc error perfect is impossible

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#336]
1:14 "one, the" should be "1-D"

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/b78ec22c-5afe-444b-8719-b390bd2b2988/lessons/dd98d695-14f1-40e0-adc5-e9fafe556f73/concepts/100acf3c-8bdf-401b-a3f6-22e6fe680bfb

**Comment by aurinalam** [comment]
Fixed
