### ISSUE TITLE
cc error Simple control diagrams

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#337]
1:34 "go" should be "grow"

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/b78ec22c-5afe-444b-8719-b390bd2b2988/lessons/dd98d695-14f1-40e0-adc5-e9fafe556f73/concepts/bc9a6bce-b6e1-4c33-8c91-1d6318f80381

**Comment by aurinalam** [comment]
Fixed
