### ISSUE TITLE
cc error PID Incorporating feedforward control

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#338]
1:22 "arrows" should be "errors"

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/b78ec22c-5afe-444b-8719-b390bd2b2988/lessons/dd98d695-14f1-40e0-adc5-e9fafe556f73/concepts/eb1ff4a3-b0f0-400f-8553-b92295447c25

**Comment by aurinalam** [comment]
Fixed
