### ISSUE TITLE
cc error tracking rotations in 3d

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#339]
1:00, 1:08  "build" should be "world"

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/b78ec22c-5afe-444b-8719-b390bd2b2988/lessons/2263120a-a3c4-4b5a-9a96-ac3e1dbae179/concepts/def1894d-ac59-42c9-a359-081274569487

**Comment by aurinalam** [comment]
Fixed.
