### ISSUE TITLE
wrong english subtitle for Kalman filter in Lesson 18

### ISSUE THREAD

**Issue by ywiyogo** [udacity/fcnd-issue-reports#349]
Kalman filter is translated as common filter in lesson 16 and 18.

**Comment by aurinalam** [comment]
Fixed! Thank you for reporting. 

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/19b5af05-2ec7-491a-94db-1befc15d07c0/lessons/8f586008-3e4f-47a1-bde5-e43c184b49d2/concepts/3cfd400d-f659-4f05-b52e-3e74a47baab7

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/19b5af05-2ec7-491a-94db-1befc15d07c0/lessons/8f586008-3e4f-47a1-bde5-e43c184b49d2/concepts/6b6f5a9f-9961-48c4-bb87-38a7567aa664?contentVersion=1.0.0&contentLocale=en-us

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/19b5af05-2ec7-491a-94db-1befc15d07c0/lessons/8f586008-3e4f-47a1-bde5-e43c184b49d2/concepts/3cfd400d-f659-4f05-b52e-3e74a47baab7?contentVersion=1.0.0&contentLocale=en-us

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/19b5af05-2ec7-491a-94db-1befc15d07c0/lessons/8f586008-3e4f-47a1-bde5-e43c184b49d2/concepts/9e7ca17a-a4ea-4133-a415-c766b315e2c0?contentVersion=1.0.0&contentLocale=en-us

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/19b5af05-2ec7-491a-94db-1befc15d07c0/lessons/8f586008-3e4f-47a1-bde5-e43c184b49d2/concepts/35d1767d-1570-48cc-96dd-356a80c6d55e?contentVersion=1.0.0&contentLocale=en-us

https://classroom.udacity.com/nanodegrees/nd787/parts/5aa0a956-4418-4a41-846f-cb7ea63349b3/modules/19b5af05-2ec7-491a-94db-1befc15d07c0/lessons/8f586008-3e4f-47a1-bde5-e43c184b49d2/concepts/616d0596-f236-4d6c-8da7-720e113d0481?contentVersion=1.0.0&contentLocale=en-us
