### ISSUE TITLE
Windows Version has suspected files to Norton AV

### ISSUE THREAD

**Issue by Ahmed-Shabrawy** [udacity/fcnd-issue-reports#35]
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
File: C:\Users\ashabraw\Downloads\windows\FCND-Sim_Windows.exe

**Comment by domluna** [comment]
AFAIK this means it doesn't recognize the binary among a "community".  It looks like we have to pay to be part of the community or something along those lines. Anyway, you can ignore it.
