### ISSUE TITLE
L21: Sesnor Fusion Ex missing required file

### ISSUE THREAD

**Issue by fierval** [udacity/fcnd-issue-reports#350]
The directory where the Sensor Fusion exercise is located is missing utils.py.

**Comment by fierval** [comment]
![utilspy.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aef5ec115dd020013d07320/125516c66e82c728ace21e0d46fd80932f9193b0cda5fd53b652fa912a5265296b51a27d21d6bb79ed1b29580a574fac415a5817afaf8128a4a42062c80d55b98e30063e937f03a6aa8317b500bf22834c86bfb48e4fc6e93537aa.png)

**Comment by annerajb** [comment]
yup even after refreshing workspace it does not show up.

**Comment by mvirgo** [comment]
Took a year apparently, but have added this file in now.
