### ISSUE TITLE
L21: Sensor Fusion Ex pointing to a wrong colliders.csv

### ISSUE THREAD

**Issue by fierval** [udacity/fcnd-issue-reports#351]
data = np.loadtxt('data/colliders.csv', delimiter=',', dtype='Float64', skiprows=2)

should be:
data = np.loadtxt('colliders.csv', delimiter=',', dtype='Float64', skiprows=2)

**Comment by annerajb** [comment]
can confirm even after a workspace refresh/reset

**Comment by mvirgo** [comment]
Fixed (finally)
