### ISSUE TITLE
FixedWing.L2.7 Rotation Matrices Excercise typo

### ISSUE THREAD

**Issue by xcarnd** [udacity/fcnd-issue-reports#372]
There's a typo in the text cell right above the 4th python cell. Original text:

> As a test transform frames from the world to the wind and then from the wind to the body frame and make sure that it is the same as the transformation from the wind frame to the body.

where: 
....make sure that it is the same as the transformation from the `wind` frame to the body
should be:
....make sure that it is the same as the transformation from the `world` frame to the body

**Comment by AndyAtUdacity** [comment]
Fixed!
