### ISSUE TITLE
Inconsistency in use of Phases and States(lesson and project)

### ISSUE THREAD

**Issue by Sagar-Jarvis** [udacity/fcnd-issue-reports#38]
In the lesson, Andy says States are overused and so uses Phases but in the project we again use States.

**Comment by Sagar-Jarvis** [comment]
Forgot to mention the lesson: 11) Phases of Flight

**Comment by asimonov** [comment]
yes, I noticed it too

**Comment by jtuckerdunn** [comment]
Merged with issue 47
