### ISSUE TITLE
Importance of Euclidean distance

### ISSUE THREAD

**Issue by Sagar-Jarvis** [udacity/fcnd-issue-reports#39]
There can be an extra lesson on Euclidean distance(just reading material on what and how it can help in the present project) or under the tips section for the project having tips on Euclidean distance will help students.

**Comment by ryan-keenan** [comment]
Is this a suggestion for the planning material?  Like in heuristics section?

**Comment by ryan-keenan** [comment]
Closing this issue for now.  Please feel free to reopen with suggestions for improvement!
