### ISSUE TITLE
(Peter Rho) Lesson 2 - Item 2. History - Two typos in Quiz

### ISSUE THREAD

**Issue by perh70** [udacity/fcnd-issue-reports#4]
(Peter Rho) Lesson 2 - Item 2. History - Two typos in Quiz
The word "The" in Quiz question 2 and 3 should be "They" in the following sentences:
"The designed an aircraft with adjustable wing shape" and 
"The used a biplane design with two wings"

Here's the link to the page:
https://classroom.udacity.com/courses/ud787-preview/lessons/35850006-650e-483f-a46f-c3a58809cbf0/concepts/9185a4b4-af43-4550-9dfb-21a40009efdb

**Comment by AndyAtUdacity** [comment]
Already fixed when I got to it (thanks whoever did that)
