### ISSUE TITLE
Linux Simulator

### ISSUE THREAD

**Issue by abhiojha8** [udacity/fcnd-issue-reports#43]

**Comment by abhiojha8** [comment]
The linux simulator didn't work for me on a native ubuntu 16.04 installation. I will again check this at my end and see if it could be solved. Are there any dependencies to run it? Or does it need python 2 or python 3 sourced in the terminal?

**Comment by Sagar-Jarvis** [comment]
Davinder has resolved it seems. Issue 17 has the solution from what I have seen him posting on the slack.

**Comment by davinderc** [comment]
Yeah, I believe the github repository of udacidrone has been updated, but it just needed pymavlink version 2.2.8, as 2.2.0 was acting weird.

**Comment by jtuckerdunn** [comment]
pymavlink version should solve linux environment issue
