### ISSUE TITLE
Scroll wheel zooms on resolution selector

### ISSUE THREAD

**Issue by davinderc** [udacity/fcnd-issue-reports#44]
When I scroll on the scroll bar in the resolution selector, the camera view zooms accordingly. I'm pretty sure the camera should only zoom if my cursor is not over the resolution selector.

**Comment by demi180** [comment]
Fix coming in next release. Thank you.

**Comment by domluna** [comment]
New release -> https://github.com/udacity/FCND-Simulator-Releases/releases/tag/v0.0.4-preview

no more scroll bar so closing this
