### ISSUE TITLE
'self.Phases' vs 'self.States' in preview course

### ISSUE THREAD

**Issue by berndrietberg** [udacity/fcnd-issue-reports#47]
In the third lesson, we design a solution based on a backyard_flyer.py example setup.
We learn in the videos that the drone will go through certain 'phases' (not 'states'), but in the backbone backyard_flyer.py, self.States is still used.

Solution: change all .States to .Phases.

**Comment by berndrietberg** [comment]
If you're changing this, see also my new posted issue about the Backyard Flyer Solution target_position[0:2] .

**Comment by jtuckerdunn** [comment]
Language was added to the classroom referencing that states and phases are used interchangeably.
