### ISSUE TITLE
A footnote in lesson 1, chapter 4 video which doesn't belong there

### ISSUE THREAD

**Issue by Sagar-Jarvis** [udacity/fcnd-issue-reports#49]
Lesson 1 Planning a Search: Chapter 4: Video: time tag: 0.14.

There is a footnote in the video for a 1-2secs and I don't think it belongs in that video. It's a note to designer/animator.

**Comment by ryan-keenan** [comment]
Yes all these videos are just cut with rough storyboards for now.  Fancy design and animation coming soon!
