### ISSUE TITLE
Lesson 2.2 History of Autonomous Flight Video rendering issues

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#5]
https://classroom.udacity.com/courses/ud787-preview/lessons/35850006-650e-483f-a46f-c3a58809cbf0/concepts/9185a4b4-af43-4550-9dfb-21a40009efdb

The video has some rendering bugs. 

at 0:50 the video flashes green.

Green lines flash across the screen starting at 0:55 and continuing throughout the video

white lines on image at 1:40

Background seems to cut into Nick's head sometimes. Noticeable at 2:05

**Comment by ryan-keenan** [comment]
Larry is going to take a look at this and re-upload to CoCo

**Comment by LarryMad** [comment]
@ryan-keenan I fixed the green flashes, but can't find where this video is staged in CoCo, can you supply me with the link?
