### ISSUE TITLE
2.1.13 Cost Notebook

### ISSUE THREAD

**Issue by davinderc** [udacity/fcnd-issue-reports#52]
Under the condition to check if the cost is lower, the visited dictionary's `current_vert` entry is updated, but it should be the `next_vert`. Since this line isn't in the TODO section, it can cause confusion for students when they don't get the same answer as the solution.

**Comment by domluna** [comment]
@davinderc The exercise has been updated, uses a grid instead of a graph since graphs aren't discussed until Lesson 3. The `branch` data structure is automatically updated (don't have to edit it) so this should no longer be an issue.
