### ISSUE TITLE
2.2.13: Error in Configuration Space Notebook solution

### ISSUE THREAD

**Issue by royveshovda** [udacity/fcnd-issue-reports#54]
The section "Reading the map" in the solution notebook tries to read the colliders from file. However the file 'colliders.csv' does not exist in the workspace of the notebook, and is not able to load. I am not sure if the solution notebooks are suppose to work, but this seems a small thing to fix to get this solution to work.

**Comment by orenmeiri** [comment]
strange (or update), I can run solution notebook

**Comment by domluna** [comment]
@royveshovda the colliders file was missing from the solution notebook, it's there now.
