### ISSUE TITLE
run code before simulator

### ISSUE THREAD

**Issue by orenmeiri** [udacity/fcnd-issue-reports#57]
In backyard flyer, if you run code before starting the simulator it exits on an error. It would great if the project code can wait for a connection (much like SDCND projects).

**Comment by jtuckerdunn** [comment]
@ryan-keenan is this something that can be easily implemented for all of our projects?

**Comment by ryan-keenan** [comment]
@jtuckerdunn I'm not sure what it takes to implement this but sounds like something that needs to happen on the Python side, perhaps within udacidrone.

**Comment by domluna** [comment]
https://github.com/udacity/udacidrone/pull/46
