### ISSUE TITLE
BYF Environment setup add install git step

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#59]
https://classroom.udacity.com/nanodegrees/nd787-beta/parts/38fbf270-3dd1-43e8-bf32-fc6bef248454/modules/129fb574-4a4a-4d07-a084-bc2855610afe/lessons/13c0ca8d-b11e-405a-a831-6ca38cb60246/concepts/6d8be91e-0df2-4558-8723-727cf9b64243

Add instructions to make sure git is installed before the "git clone https://github.com/udacity/FCND-Term1-Starter-Kit.git" command

**Comment by AndyAtUdacity** [comment]
Added this as a step 0 in the "detailed instructions" but not the "quick instructions". I assume students going through the quick instructions already have git.
