### ISSUE TITLE
Lesson 2.4 Quadrotor Components Video rendering issues

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#6]
https://classroom.udacity.com/courses/ud787-preview/lessons/35850006-650e-483f-a46f-c3a58809cbf0/concepts/3bebd9b3-6eca-474d-ad48-4129689fef1a

Video rendering issues:

Green lines flash on screen at 0:43
Green screen flash at 0:47, 0:55
wires on quads disappear in background around 1:20

**Comment by ryan-keenan** [comment]
Larry is going to look into this and re-upload videos to CoCo

**Comment by LarryMad** [comment]
@ryan-keenan I fixed the green flashes, but can't find where this video is staged in CoCo, can you supply me with the link?
