### ISSUE TITLE
pandas is not part of fcnd python environment

### ISSUE THREAD

**Issue by asimonov** [udacity/fcnd-issue-reports#62]
in configuration space notebook pandas is used.
but when I run it locally it shows that pandas is not part of environment.
may be good idea to add it to yaml file

**Comment by ryan-keenan** [comment]
Thanks for catching this! Agreed. pandas is not necessary here and we're getting rid of it.  Will update here when done .

**Comment by domluna** [comment]
@ryan-keenan can we close this?

**Comment by ryan-keenan** [comment]
Yep looks like all the pandas are back in the zoo, or out of our zoo... or something. no more pandas.
