### ISSUE TITLE
links to solution notebooks dont work

### ISSUE THREAD

**Issue by asimonov** [udacity/fcnd-issue-reports#64]
for example if I click link inside bresenham notebook to 'solution' it shows me an error message. not sure if it should work in beta or only supposed to work in final FCND

**Comment by delvingdeep** [comment]
![Screen Shot 2018-02-18 at 7.21.11 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59152178d5571c0020cf1e52/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455fb6b7191a37ff1102a4f5e5e5ecc3c4a4356bcbbd671f3e57862804e0ebcd76c5c7cc73f18aeb1d717be01ba228c1cd6e0b4894ed2f42f67b6d5db1063474f4dcbed5727a19141c95df742e14d55a4133264e5712431.png)

Shows the above error message

**Comment by ryan-keenan** [comment]
Thanks Deep!  Should be fixed now for all notebooks
