### ISSUE TITLE
Simulator crashes on Linux machine

### ISSUE THREAD

**Issue by AndyAtUdacity** [udacity/fcnd-issue-reports#65]
This was reported by a student in slack. Student's name is @I_ohm_Sri

He first reported: "Hi, in Ubuntu, simulator software is not opening, it just opened and closed automatically with in a second. Else packages are cool, I imported and checked"

When I asked if he had the correct sim version for his machine he said "Yup I tried both the version. If you want I will send a video of that process. 
I just download linux-universal, it contains both file u mentioned above. I tried both, one is not even open, other one opened and closed immediately."

**Comment by mimoralea** [comment]
I was able to run in Arch Linux, but I can't interact with the simulator.

I arm the drone, press the spacebar and it goes crazy. ~5 seconds later is -1000 meters altitude.

![Alt text](https://i.imgur.com/yWy5F8n.png "Optional title")

Reproducible 100% of the times.

**Comment by demi180** [comment]
@AndyAtUdacity could you please ask him to get us the player log for it? it'll be at ~/.config/unity3d/CompanyName/ProductName/Player.log in Linux.

**Comment by ryan-keenan** [comment]
I'm gonna guess this is closed now with the new releases of the sim.  Haven't heard this from anyone else.  I'll close now but feel free to reopen if the issue persists
