### ISSUE TITLE
2.3.2 Voice rendering issue

### ISSUE THREAD

**Issue by delvingdeep** [udacity/fcnd-issue-reports#66]
In `3D Motion planning`, module 3:`Graph Representation` Lesson 2-`Waypoint Extraction`, For 0:00 to 0:03 Voice pitch is different from the regular one, and needs to be corrected.

**Comment by delvingdeep** [comment]
Same issue with the voice in Lesson  2.3.3 `Collinearity` from 0:01 to 0:15

**Comment by jtuckerdunn** [comment]
This issue is being tracked with #72
