### ISSUE TITLE
Broken Link: Collinearity_Condition-starter Solution Link

### ISSUE THREAD

**Issue by matthewzimmer** [udacity/fcnd-issue-reports#67]
Classroom:

https://classroom.udacity.com/nanodegrees/nd787-beta/parts/1822bb5b-8b4b-496e-80b5-ab74d031113b/modules/8c3efada-ac9a-4a6a-bc77-4036137f56c6/lessons/5a623140-3e28-4ef1-a0f2-104715381c54/concepts/286f789f-bf70-4896-b41c-68907a0c9825

Appears to be broken:

https://cocoview9d7db0d8.udacity-student-workspaces.com/notebooks/Collinearity-Solution.ipynb

**Comment by matthewzimmer** [comment]
![Screen Shot 2018-02-19 at 12.28.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5812e6f9a05b360e006e4b9c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216455fa6b7191a379ed0c2959415b48bc30254d58eeb9cb74fce36f34985619e8806b5e77ce3c13a5ba8b4ab700ba208948d6e5ea824fc2fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae84d54ac123264e77f3e6e0a.png)

**Comment by jtuckerdunn** [comment]
This issue is being tracked in #64
