### ISSUE TITLE
Deadbands video animation changes

### ISSUE THREAD

**Issue by jtuckerdunn** [udacity/fcnd-issue-reports#74]
For the deadbands video animations should the deadband circles be moving with the waypoints to show uncertainty instead of being fixed in one location? 2.3.23 video deadbands
https://classroom.udacity.com/nanodegrees/nd787-beta/parts/1822bb5b-8b4b-496e-80b5-ab74d031113b/modules/8c3efada-ac9a-4a6a-bc77-4036137f56c6/lessons/5a623140-3e28-4ef1-a0f2-104715381c54/concepts/5dc6f119-f8e7-41eb-9fcc-86b0683dbc1a

**Comment by ryan-keenan** [comment]
Great catch!  Fixed now.
