### ISSUE TITLE
Voronoi based path notebook has use of Dijkstra but no mention of that before

### ISSUE THREAD

**Issue by Sagar-Jarvis** [udacity/fcnd-issue-reports#76]
It uses Dijkstra.py but nowhere in the lessons it's explained or even mentioned what is Dijkstra or which type search method is that. Having a panel explaining that will help students.

**Comment by jtuckerdunn** [comment]
https://classroom.udacity.com/nanodegrees/nd787-beta/parts/1822bb5b-8b4b-496e-80b5-ab74d031113b/modules/8c3efada-ac9a-4a6a-bc77-4036137f56c6/lessons/5a623140-3e28-4ef1-a0f2-104715381c54/concepts/356c6f40-5a4d-4441-97b3-f2e303be8dc9 Link to referenced notebook

**Comment by ryan-keenan** [comment]
Thanks for reporting! We're updating this notebook and the new version won't include dijkstra

**Comment by ryan-keenan** [comment]
ok updated now
