### ISSUE TITLE
Lack of good comments in the solution notebooks

### ISSUE THREAD

**Issue by Sagar-Jarvis** [udacity/fcnd-issue-reports#78]
Comments on the important parts of the code will help students. Like in Configuration space notebook(lesson 2,ch: 14) having a line of comment beside x_min, x_max, etc will help why we use it in the obstacle. And a small comments beside obstacle about how it uses x_min and safe_distance to map the obstacles. Helping here will help students when they reach in the 3D part of the code later in lessons.

Not only here but in all solution notebooks, we can have more helpful comments for the most important parts of the code.

**Comment by ryan-keenan** [comment]
Thanks for reporting this.  We're updating all the notebooks prior to launch so comments should be much better.
