### ISSUE TITLE
We could have more explanation below the Voronoi video.

### ISSUE THREAD

**Issue by Sagar-Jarvis** [udacity/fcnd-issue-reports#80]
Below the Voronoi video, we can have more explanation with some diagrams. Like for example:

Giving an example of how circumcircle for the triangle is the base for this Voronoi diagram will help. How the perpendicular bisectors and the circumcenter come in play for the voronoi graphs.

Just that giving more reading material below the video about voronoi graphs will help. Even a quiz asking to work on the vornoi graph will help.

**Comment by ryan-keenan** [comment]
there is now a good notebook exercise after the Voronoi video.  I think it addresses most of these concerns so I'll close this.  Thanks for the feedback!
