### ISSUE TITLE
Partial and possible plans

### ISSUE THREAD

**Issue by jaketlussier** [udacity/fcnd-issue-reports#81]
Find this notation a bit confusing:
plan1 = [start] action = up
plan2 = [start] action = right
....

Can we somehow make use of notation like
possible_plans = [
 [start]
 [start, x1] (from action right)
 [start, x2] (from action up)
 ...
]

**Comment by ryan-keenan** [comment]
Agreed, this is a poor choice of notation.  We can modify the text in these videos fairly easily and will put this on the list of TODOs!

**Comment by ryan-keenan** [comment]
Didn't mean to close this, but not sure how to reopen
