### ISSUE TITLE
chrome scrolling

### ISSUE THREAD

**Issue by orenmeiri** [udacity/fcnd-issue-reports#84]
section 2: 3d motion planning has 5 sections + project. When scrolling this list in chrome it gets stuck often. I never encountered this in any nanodegree I visited. I checked on safari and it works fine.

my environment:
macbookPro Mid 2012, High Sierra macOS
chrome 64.0.3282.167

**Comment by ryan-keenan** [comment]
Thanks for reporting! I see this as well, will look into it.

**Comment by ryan-keenan** [comment]
I've reported this to our Classroom dev team.  Will update here once it's solved.

**Comment by ryan-keenan** [comment]
This is fixed now :)
