### ISSUE TITLE
motion planning project: global_map

### ISSUE THREAD

**Issue by orenmeiri** [udacity/fcnd-issue-reports#85]
I couldn't find global_map defined anywhere for the project environment. Please provide it to students in a clear place.

**Comment by orenmeiri** [comment]
I'm talking about GPS coordinates here :-)

**Comment by ryan-keenan** [comment]
Hey sorry I missed this until now!  Is this still an issue?  The project has been revamped significantly in the last two weeks so hopefully this is resolved.  I'll close this issue for now but if it's still a problem feel free to reopen.  Thanks!
