### ISSUE TITLE
Indices in BFS exercise

### ISSUE THREAD

**Issue by nick-roy** [udacity/fcnd-issue-reports#90]

**Comment by nick-roy** [comment]
When we say "you'll eventually be representing (x, y) positions on a map of the world as (i, j) positions within an array so take care to keep track of your indices!" I am not sure what we are trying to keep track of. Can we add more text to say what the issue here is that the students should be careful about?

**Comment by ryan-keenan** [comment]
Thanks for pointing this out Nick. I removed this caveat because it isn't relevant to this exercise.  I'll try to find a place for it later when we're actually using (x, y, z) and representing things in a grid.
