### ISSUE TITLE
Exercises : 1 vs many

### ISSUE THREAD

**Issue by nick-roy** [udacity/fcnd-issue-reports#92]
It would be good to make clear for the exercises when the student needs choose one option versus choose all that apply. This seems especially important for Lesson 5  - Search space and  Lesson 5  - Grid representation

**Comment by ryan-keenan** [comment]
Good point!  I've made this change adding "(choose all that apply)" to check button quizzes.  Since you can only choose one for radio buttons quizzes I figure it's self explanatory.  I'm planning to add more check button quizzes and will do the same wherever they appear.
