### ISSUE TITLE
"Vehicle Representations"

### ISSUE THREAD

**Issue by nick-roy** [udacity/fcnd-issue-reports#93]
The lesson title of "Vehicle Representations" is a little generic and not particularly accurate. Maybe "How to Represent the World of the Flying Car" or "Flying Car Representations"?

**Comment by ryan-keenan** [comment]
I've changed it to "Flying Car Representations". It's nice if you can see at least most of the title in the side bar so best to keep it short where possible.  Super easy to change this again so we can iterate if better ideas surface.
