### ISSUE TITLE
Geodetic to NED Exercise intro

### ISSUE THREAD

**Issue by jaketlussier** [udacity/fcnd-issue-reports#94]
Consider dropping intro in notebook (it's redundant and a bit choppy) and modifying the classroom intro with something like this:

"Now that you've learned the fundamentals of coordinate systems, you'll get hands-on experience implementing a global_to_local function that converts from global geodetic (latitude and longitude) to global NED (north, east, down, zone) to local NED (north, east, down relative to a "home"). You will also implement the local_to_global function that does the opposite.

For the purposes of this exercise, we will assume that all positions are in the same UTM zone. So when we convert from global geodetic to global NED, you can simply ignore the zone. But keep in mind that in order to go back to geodetic coordinates from NED you need to first convert to UTM and specify the zone number and letter as well as actual eastings and northings in the zone!

To convert from global NED to local NED, you will take the north and east difference between your global NED and another "home" NED point. You can assume that the zero position of the "altitude" and "down" axes correspond to the same place along the z-axis, so the transformation of that coordinate just requires multiplying by -1.

Good luck! And to have a peek at the solution scroll to the link at the bottom of the notebook."

**Comment by ryan-keenan** [comment]
Thanks for reworking this!  I think that it makes more sense to say UTM instead of "global NED", since that's really what that middle step is.  I reworded a bit but retained the gist of what you're clearing up here.
