### ISSUE TITLE
Geodetic to NED Exercise student code?

### ISSUE THREAD

**Issue by jaketlussier** [udacity/fcnd-issue-reports#95]
Do we want the student to implement something in this exercise? One idea would be to not reset local_coordinates_NED nor geodetic_home_coordinates, ask the student to convert back, and then assert difference is less than admissable.

**Comment by ryan-keenan** [comment]
Would be fine by me to add more to this exercise but in reality this stuff is already implemented for them in the Drone API.  This is more a prompt for them to learn a little about what's going on under the hood and maybe dig around a little more in the API to see what's going on.
