### ISSUE TITLE
Gimbal lock

### ISSUE THREAD

**Issue by jaketlussier** [udacity/fcnd-issue-reports#97]
For next rev, discuss Gimbal Lock graphic

**Comment by ryan-keenan** [comment]
Now have a gif and link in two places to download gimbal demo simulator in classroom.  I think this will help a lot with this concept!  https://classroom.udacity.com/nanodegrees/nd787-beta/parts/1822bb5b-8b4b-496e-80b5-ab74d031113b/modules/8c3efada-ac9a-4a6a-bc77-4036137f56c6/lessons/91ccafae-d090-4144-a8f3-06cb8ac10757/concepts/4f46ba05-3e7e-4086-9ea7-78c6fbfe12be
